package snippetscan

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	licensedomain "github.com/eitanity/kanonarion/internal/license/domain"
)

const block = `package p

// SPDX-SnippetBegin
// SPDX-SnippetCopyrightText: Copyright 2023 Google LLC
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-SnippetComment: Transcribed from github.com/google/capslock@v0.3.2
// SPDX-SnippetEnd
`

func write(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestScan_FindsBlockInFirstPartySource(t *testing.T) {
	root := t.TempDir()
	write(t, root, "internal/a/a.go", block)

	atts, err := New(root).Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(atts) != 1 {
		t.Fatalf("want 1 attribution, got %d", len(atts))
	}
	if atts[0].SourcePath != "internal/a/a.go" {
		t.Errorf("SourcePath = %q, want a slash-separated path relative to the root", atts[0].SourcePath)
	}
}

// Excluded trees must not contribute attributions — and, critically, a
// malformed block inside one must not fail a real scan. testdata holds
// deliberately broken fixtures; vendor holds module copies that module licence
// extraction already covers.
func TestScan_ExcludesNonFirstPartySource(t *testing.T) {
	malformed := strings.Replace(block, "// SPDX-License-Identifier: BSD-3-Clause\n", "", 1)

	root := t.TempDir()
	write(t, root, "internal/a/a_test.go", block)
	write(t, root, "internal/a/gen.go", "// Code generated by stringer. DO NOT EDIT.\n"+block)
	write(t, root, "internal/a/testdata/broken.go", malformed)
	write(t, root, "vendor/example.com/dep/dep.go", block)
	write(t, root, ".git/hooks/hook.go", block)
	write(t, root, "internal/a/notes.txt", block)

	atts, err := New(root).Scan()
	if err != nil {
		t.Fatalf("excluded trees must not fail the scan: %v", err)
	}
	if len(atts) != 0 {
		t.Fatalf("want 0 attributions, got %d: %+v", len(atts), atts)
	}
}

// A generated file is skipped even when the marker is not on the first line —
// it follows the build tags and package clause in real generated output.
func TestScan_ExcludesGeneratedFileWithLeadingBuildTag(t *testing.T) {
	root := t.TempDir()
	write(t, root, "internal/a/gen.go", "//go:build linux\n\n// Code generated by mockgen. DO NOT EDIT.\n"+block)

	atts, err := New(root).Scan()
	if err != nil {
		t.Fatal(err)
	}
	if len(atts) != 0 {
		t.Fatalf("want 0 attributions, got %d", len(atts))
	}
}

// A malformed block in real first-party source fails the whole scan: the
// caller is building an attribution document, and a partial scan would publish
// one that looks complete.
func TestScan_MalformedBlockFailsScan(t *testing.T) {
	root := t.TempDir()
	write(t, root, "internal/a/a.go", strings.Replace(block, "// SPDX-SnippetEnd\n", "", 1))

	_, err := New(root).Scan()
	if err == nil {
		t.Fatal("want an error, got none")
	}
	if !errors.Is(err, licensedomain.ErrMalformedSnippet) {
		t.Errorf("error should wrap ErrMalformedSnippet, got: %v", err)
	}
}

// The scan is a no-op on a tree with no tagged source, which is the common case.
func TestScan_NoSnippets(t *testing.T) {
	root := t.TempDir()
	write(t, root, "internal/a/a.go", "package p\n\nvar x = 1\n")

	atts, err := New(root).Scan()
	if err != nil {
		t.Fatal(err)
	}
	if len(atts) != 0 {
		t.Fatalf("want 0 attributions, got %d", len(atts))
	}
}
