package godoc_test

import (
	"context"
	"testing"
	"testing/fstest"

	"github.com/eitanity/kanonarion/internal/iface/domain"
)

// FuzzExtract feeds arbitrary Go source text to the iface godoc extractor as a
// single-file in-memory module tree. Source text from arbitrary modules is
// untrusted go/parser input ( relates). The extractor
// must degrade gracefully: never panic, never return an error for unparseable
// source, and record a ParseFailure (Partial status) rather than crashing.
//
// Run locally with:
//
//	go test -run=NONE -fuzz=FuzzExtract./internal/iface/adapters/extractor/godoc
func FuzzExtract(f *testing.F) {
	seeds := []string{
		// Valid: exported type + method + generic func.
		`package p

// Client does things.
type Client struct{ N int }

func (c *Client) Do() error { return nil }

func Map[T any](xs []T, fn func(T) T) []T { return xs }
`,
		// Syntactically broken.
		"package p\nfunc (",
		"package",
		"",
		"package p\n}{)(",
		// Pathological generics.
		"package p\nfunc F[T any, U interface{ ~int | ~string }]() {}\n",
		"package p\ntype T[A, B, C any] struct{ X A; Y B; Z C }\n",
		"package p\nfunc F[" + "T " + "any]() {}\n",
		// Huge identifier.
		"package p\nvar " + repeat("a", 1<<16) + " = 1\n",
		// Deeply nested expression.
		"package p\nvar x = " + repeat("(", 4096) + "1" + repeat(")", 4096) + "\n",
		// Invalid UTF-8 in source / identifiers / comments.
		"package p\n// \xff\xfe\xfd\nvar X = 1\n",
		"package p\nvar \xff\xfe = 1\n",
		// Generated-file marker (exercises isGeneratedFile path).
		"// Code generated by tool. DO NOT EDIT.\npackage p\n\ntype T struct{}\n",
		// Non-ASCII / unusual but valid identifiers.
		"package p\ntype Δ struct{}\nfunc (Δ) Method() {}\n",
		// cgo + build constraints.
		"//go:build linux\n\npackage p\nimport \"C\"\nfunc F() {}\n",
	}
	for _, s := range seeds {
		f.Add(s)
	}

	ext := makeExtractor()
	c := coord(f)

	f.Fuzz(func(t *testing.T, src string) {
		fsys := fstest.MapFS{
			"a.go": &fstest.MapFile{Data: []byte(src)},
		}

		// Contract: no panic, and no error for arbitrary source — bad source
		// is reported via OverallStatus / ParseFailures, never as an error.
		rec, err := ext.Extract(context.Background(), fsys, c)
		if err != nil {
			t.Fatalf("Extract returned an error for fuzzed source (must be graceful): %v", err)
		}

		switch rec.OverallStatus {
		case domain.InterfaceStatusExtracted,
			domain.InterfaceStatusPartial,
			domain.InterfaceStatusCancelled:
			// expected graceful outcomes
		default:
			t.Fatalf("Extract returned unexpected OverallStatus %v for source %q",
				rec.OverallStatus, src)
		}
	})
}

func repeat(s string, n int) string {
	b := make([]byte, 0, len(s)*n)
	for range n {
		b = append(b, s...)
	}
	return string(b)
}
